### ISSUE TITLE
Summary of results and logging

### ISSUE THREAD

**Issue by mandel01** [mandel01/pyinseq#7]
Need overall strategy for logging results into a text file and into the terminal.

**Comment by mandel01** [comment]
`sys.stdout.write('\r' + 'Records processed ... {:,}'.format(nreads))` works to update the terminal without cascading. It's in the new demultiplex.py -- not fully integrated into the pipeline yet, maybe tomorrow. Will do this for now, then work on a proper log once everything is functional with the new workflow.

**Comment by mandel01** [comment]
Progress with samplesDict here - https://github.com/mandel01/pyinseq/commit/38e830e7984812f5c2260f092699a7a0bf544a5f

**Comment by mandel01** [comment]
Messages to stdout are greatly improved with https://github.com/mandel01/pyinseq/commit/ef89a93878fa0ac68c15f02595dc2044299a82be and the preceding ~6 commits. Running `make` gives the output below. Still need the following:

- Better documentation after the `'Demultiplexing data/example/example01.fastq into the following barcoded files:`
- Additional messaging to describe number of reads filtered/discarded at each step.
- Logging of this information in a file. Some of the information is from `bowtie` and will need to be captured, or otherwise calculated.
 

```

Making directory: results/example01
Making directory: results/example01/raw_data/
Making directory: results/example01/genome_lookup/

Processing 2 total samples:
E001_01
  barcode: GAAG
E001_02
  barcode: CTTT
Sample details written to results/example01/samples.yaml

Demultiplexing data/example/example01.fastq into the following barcoded files:
Records processed ... 82

Preparing nucleotide fasta file from GenBank file to use in bowtie mapping.
  GenBank source file:  data/example/ES114v2.gb
  Nucleotide file output file: results/example01/genome_lookup/genome.fna

Preparing feature table file from GenBank file to use in gene mapping.
  GenBank source file:  data/example/ES114v2.gb
  Feature table output file: results/example01/genome_lookup/genome.ftt

Building bowtie index files in results/example01/genome_lookup

Processing sample E001_01
Records processed ... 40
Mapping E001_01 reads to bowtie
# reads processed: 40
# reads with at least one reported alignment: 40 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 40 alignments to 1 output stream(s)

Processing sample E001_02
Records processed ... 40
Mapping E001_02 reads to bowtie
# reads processed: 40
# reads with at least one reported alignment: 40 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 40 alignments to 1 output stream(s)
python test/test.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.123s

OK
```

**Comment by mandel01** [comment]
Consider incorporating the [tqdm progress bar](https://github.com/noamraph/tqdm)

**Comment by biobenkj** [comment]
Not to overlap work done here, but is this issue about to be closed or can I take a crack at it?

**Comment by mandel01** [comment]
Hey @biobenkj I've got some unpushed commits here to capture and parse the bowtie output. Let me try to wrap that up and push.

**Comment by mandel01** [comment]
Ok I pushed/merged what I have. Let me know if you can jump in here or if this is too messy.

I think there are three objectives here. First is to output the key results in a human-readable format. Second is to output key results in a format that can be grabbed for plotting and analysis. Third is to have a output format written to the results/{experiment} folder that describes the samples and relevant file paths so that subsequent analyses of samples from different experiments (or re-run from the same experiment) doesn't require a new demultiplexing and can be done quickly. 

I think we're halfway there.

In `pyinseq.py` the `logdata` dictionary collects information for each sample and is partially redundant with the `samplesDict` ordered dictionary (see yaml outputs below). Here are thoughts for next steps...

- changing total_reads to no_barcode so that each `logdata` dictionary key is a separate sample (or no sample)
- consolidate the samplesDict orderedDict / samples.yml and the logdata dict / samples_summary.yml into a single orderedDict and single output yaml file.
- clean up the code. Would appreciate ideas here. I was going to wait until the end to do this but perhaps it would be worth a look now. The `pyinseq.py` file is getting to be a long script... Can we do better than having the print() messages interspersed as they are. Perhaps the HTSeq link you provided would be a good hint.
- I think the progress bar and better user interaction are still good ideas but I haven't given them much thought.



##### `samplesDict` orderedDict > `samples.yml`

```yaml
!!python/object/apply:collections.OrderedDict
dictitems:
  E001_01:
    barcode: GAAG
    demultiplexedPath: results/example01/raw_data/E001_01.fastq.gz
    name: E001_01
    trimmedPath: results/example01/E001_01_trimmed.fastq
  E001_02:
    barcode: CTTT
    demultiplexedPath: results/example01/raw_data/E001_02.fastq.gz
    name: E001_02
    trimmedPath: results/example01/E001_02_trimmed.fastq
```


##### `logdata` dictionary > `samples_summary.yml`

```yaml
E001_01:
  bowtie_results:
    '# reads processed:': 40
    '# reads that failed to align:': 0
    '# reads with at least one reported alignment:': 40
  insertion_sites: 11
  reads_with_bc: 40
  reads_with_bc_seq_tn: 40
E001_02:
  bowtie_results:
    '# reads processed:': 40
    '# reads that failed to align:': 0
    '# reads with at least one reported alignment:': 40
  insertion_sites: 11
  reads_with_bc: 40
  reads_with_bc_seq_tn: 40
total_reads: 82
```

**Comment by biobenkj** [comment]
I'll have to work through this a bit :) Then I'll let you know

**Comment by mandel01** [comment]
It would benefit from another pair of eyes. Ping me with any q's.

**Comment by mandel01** [comment]
@biobenkj I edited the two dictionaries to be more logical (https://github.com/mandel01/pyinseq/pull/36)

Now:
- `samplesDict` / `samples.yml` has info for sample-level data.
- `summaryDict` / `summary.yml` has info for run-level data (so far, just total number of reads).
- `logdata` dictionary / `samples_summary.yml` were removed.

Here is the current output at the end of the example01 run:


```
Writing file with summary data for each sample:
  results/example01/samples.yml
!!python/object/apply:collections.OrderedDict
dictitems:
  E001_01:
    barcode: GAAG
    bowtie_results:
      '# reads processed:': 40
      '# reads that failed to align:': 0
      '# reads with at least one reported alignment:': 40
    demultiplexedPath: results/example01/raw_data/E001_01.fastq.gz
    insertion_sites: 11
    name: E001_01
    reads_with_bc: 40
    reads_with_bc_seq_tn: 40
    trimmedPath: results/example01/E001_01_trimmed.fastq
  E001_02:
    barcode: CTTT
    bowtie_results:
      '# reads processed:': 40
      '# reads that failed to align:': 0
      '# reads with at least one reported alignment:': 40
    demultiplexedPath: results/example01/raw_data/E001_02.fastq.gz
    insertion_sites: 11
    name: E001_02
    reads_with_bc: 40
    reads_with_bc_seq_tn: 40
    trimmedPath: results/example01/E001_02_trimmed.fastq

Writing file with overall summary information:
  results/example01/summary.yml
total reads: 82
```
